# Generated by Django 5.2 on 2025-10-12 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_analysis_detail', '0001_initial'),
        ('product', '0003_alter_product_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Precio Activo')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Activación')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_entries', to='price_analysis_detail.priceanalysisdetail', verbose_name='Detalle de Análisis de Origen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='product.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historiales de Precios',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivePrice',
            fields=[
            ],
            options={
                'verbose_name': 'Precio Activo',
                'verbose_name_plural': 'Precios Activos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('price_history.pricehistory',),
        ),
    ]
