# Generated by Django 5.2 on 2025-08-09 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
        ('quotation', '0002_alter_quotation_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha de la orden')),
                ('code', models.CharField(help_text='Código único para la orden de compra.', max_length=100, unique=True, verbose_name='código de orden')),
                ('arrival_date', models.DateTimeField(verbose_name='fecha de llegada')),
                ('status', models.BooleanField(default=None, help_text='Marcar el estatus de la orden.', verbose_name='estatus')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='provider.provider', verbose_name='proveedor')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='quotation.quotation', verbose_name='cotización')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Ordenes de Compras',
                'db_table': 'buy_order',
                'ordering': ['-date'],
            },
        ),
    ]
