# Generated by Django 5.2 on 2025-08-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_order', '0001_initial'),
        ('provider', '0001_initial'),
        ('quotation', '0002_alter_quotation_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='code',
            field=models.CharField(blank=True, editable=False, help_text='Código único para la orden de compra.', max_length=100, unique=True, verbose_name='código de orden'),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='provider.provider', verbose_name='proveedor'),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='quotation.quotation', verbose_name='cotización'),
        ),
    ]
