# Generated by Django 5.2 on 2025-08-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_order', '0002_alter_buyorder_code_alter_buyorder_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='status',
            field=models.BooleanField(default=False, help_text='Marcar el estatus de la orden.', verbose_name='estatus'),
        ),
    ]
