# Generated by Django 5.2 on 2025-10-12 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_order', '0003_alter_buyorder_status'),
        ('quotation', '0003_alter_quotation_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='quotation.quotation', verbose_name='cotización'),
        ),
    ]
