# Generated by Django 5.2 on 2025-10-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_order', '0004_alter_buyorder_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyorder',
            name='status',
        ),
        migrations.AddField(
            model_name='buyorder',
            name='is_approved',
            field=models.BooleanField(default=None, help_text='Marcar si la orden de compra ha sido aprobada.', verbose_name='aprobada'),
        ),
    ]
