# Generated by Django 5.2 on 2025-10-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_order', '0005_remove_buyorder_status_buyorder_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Marcar si la orden de compra ha sido aprobada.', verbose_name='aprobada'),
        ),
    ]
