# Generated by Django 5.2 on 2025-08-07 19:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'El nombre de la categoría es obligatorio.', 'unique': 'Ya existe una categoría con este nombre.'}, help_text='Nombre único para la categoría. Solo se permiten letras, números y espacios.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números y espacios.', regex='^[a-zA-Z0-9\\sñÑáéíóúÁÉÍÓÚ]+$')], verbose_name='nombre de la categoría')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional de la categoría.', null=True, verbose_name='descripción')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
    ]
