# Generated by Django 5.2 on 2025-08-09 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buy_order', '0001_initial'),
        ('product', '0002_alter_product_created_by_alter_product_modified_by_and_more'),
        ('unit_of_measure', '0002_alter_unitofmeasure_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio unitario')),
                ('approved_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='cantidad')),
                ('is_approved', models.BooleanField(default=None, help_text='Marcar el item ha sido aprobado.', verbose_name='aprobada')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='buy_order.buyorder', verbose_name='orden de compra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='producto')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_of_measure.unitofmeasure', verbose_name='unidad de medida')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra',
                'verbose_name_plural': 'Detalles de Ordenes de Compra',
                'db_table': 'buy_order_detail',
                'ordering': ['buy_order', 'product__name'],
            },
        ),
    ]
