# Generated by Django 5.2 on 2025-08-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy_order_detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyorderdetail',
            old_name='approved_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='buyorderdetail',
            name='is_approved',
        ),
    ]
