# Generated by Django 5.2 on 2025-08-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_order_detail', '0002_rename_approved_quantity_buyorderdetail_quantity_and_more'),
        ('product', '0002_alter_product_created_by_alter_product_modified_by_and_more'),
        ('unit_of_measure', '0002_alter_unitofmeasure_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyorderdetail',
            name='is_received',
            field=models.BooleanField(default=False, help_text='Marcar si este ítem específico ha sido recibido.', verbose_name='recibido'),
        ),
        migrations.AlterField(
            model_name='buyorderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='buyorderdetail',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unit_of_measure.unitofmeasure', verbose_name='unidad de medida'),
        ),
    ]
