# Generated by Django 5.2 on 2025-08-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationdetail',
            name='is_approved',
            field=models.BooleanField(default=None, help_text='Marcar el item ha sido aprobado.', verbose_name='aprobada'),
        ),
    ]
