# Generated by Django 5.2 on 2025-08-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_created_by_alter_product_modified_by_and_more'),
        ('quotation_detail', '0002_alter_quotationdetail_is_approved'),
        ('unit_of_measure', '0002_alter_unitofmeasure_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='quotationdetail',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unit_of_measure.unitofmeasure', verbose_name='unidad de medida'),
        ),
    ]
