# Generated by Django 5.2 on 2025-11-26 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('inventory', '0001_initial'),
        ('inventory_movement_type', '0001_initial'),
        ('product', '0003_alter_product_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.PositiveIntegerField(help_text='ID de la Compra, Venta o Traslado asociado.', verbose_name='ID de registro (origen)')),
                ('document_number', models.CharField(help_text='Factura #123, Envío #456, etc.', max_length=100, verbose_name='número de documento')),
                ('batch', models.UUIDField(verbose_name='lote (batch)')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positiva si entra, negativa si sale (visual).', max_digits=12, verbose_name='cantidad movida')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo unitario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de ingreso')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branch.branch', verbose_name='sucursal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('inventory_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex_movements', to='inventory.inventory', verbose_name='número de entrada (origen)')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_movement_type.inventorymovementtype', verbose_name='tipo de movimiento')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardex',
                'db_table': 'kardex',
                'ordering': ['-created_at'],
            },
        ),
    ]
