# Generated by Django 5.2 on 2025-08-09 16:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo o razón social del proveedor.', max_length=100, verbose_name='nombre del proveedor')),
                ('country', models.CharField(help_text='País de origen del proveedor.', max_length=100, verbose_name='país')),
                ('address', models.TextField(help_text='Dirección física completa del proveedor.', verbose_name='dirección')),
                ('phone', models.CharField(help_text='Número de teléfono de contacto.', max_length=20, validators=[django.core.validators.RegexValidator(message='El formato del teléfono no es válido. Ejemplo: +50377778888', regex='^\\+?1?\\d{8,15}$')], verbose_name='teléfono')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un proveedor registrado con este correo electrónico.'}, help_text='Dirección de correo electrónico de contacto.', max_length=100, unique=True, verbose_name='correo electrónico')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'provider',
                'ordering': ['name'],
            },
        ),
    ]
