# Generated by Django 5.2 on 2025-10-12 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_created_by_alter_category_modified_by'),
        ('subcategory', '0002_alter_subcategory_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='category.category', verbose_name='categoría padre'),
        ),
    ]
