# Generated by Django 5.2 on 2025-08-09 16:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nombre de la persona de contacto.', max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(help_text='Apellido de la persona de contacto.', max_length=100, verbose_name='apellido')),
                ('phone', models.CharField(help_text='Número de teléfono del contacto.', max_length=20, validators=[django.core.validators.RegexValidator(message='El formato del teléfono no es válido. Ejemplo: +50377778888', regex='^\\+?1?\\d{8,15}$')], verbose_name='teléfono')),
                ('email', models.EmailField(help_text='Dirección de correo electrónico del contacto.', max_length=100, verbose_name='correo electrónico')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='provider.provider', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'Contacto de Proveedor',
                'verbose_name_plural': 'Contactos de Proveedores',
                'db_table': 'provider_contact',
                'ordering': ['provider__name', 'first_name'],
            },
        ),
    ]
