# Generated by Django 5.2 on 2025-10-12 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('provider_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercontact',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='provider.provider', verbose_name='proveedor'),
        ),
    ]
