# Generated by Django 5.2 on 2025-10-12 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_analysis', '0001_initial'),
        ('product', '0003_alter_product_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAnalysisDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(editable=False, verbose_name='Cantidad')),
                ('invoice_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Costo Factura (FOB)')),
                ('final_prorated_cost', models.DecimalField(decimal_places=4, editable=False, max_digits=12, verbose_name='Costo Final Prorrateado')),
                ('utility', models.DecimalField(decimal_places=2, default=0.2, help_text='Utilidad deseada en formato decimal. Ej: 0.25 para 25%.', max_digits=5, verbose_name='Utilidad (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='price_analysis.priceanalysis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Análisis de Precio',
                'verbose_name_plural': 'Detalles de Análisis de Precios',
                'unique_together': {('analysis', 'product')},
            },
        ),
    ]
