# Generated by Django 5.2 on 2025-11-26 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('product', '0003_alter_product_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='número de entrada (UUID)')),
                ('batch', models.UUIDField(editable=False, verbose_name='lote (batch)')),
                ('original_quantity', models.DecimalField(decimal_places=2, help_text='La cantidad inicial con la que se creó este registro.', max_digits=12, verbose_name='cantidad original')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='El saldo restante de este lote específico.', max_digits=12, verbose_name='cantidad actual')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo unitario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de ingreso')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branch.branch', verbose_name='sucursal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Inventario (Por Lote)',
                'verbose_name_plural': 'Inventario (Por Lotes)',
                'db_table': 'inventory',
                'ordering': ['-created_at'],
            },
        ),
    ]
