# Generated by Django 5.2 on 2025-11-27 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('inventory', '0001_initial'),
        ('product', '0003_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('branch', 'product', 'batch')},
        ),
    ]
