# Generated by Django 5.2 on 2025-10-13 01:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_product_subcategory'),
        ('purchase', '0004_alter_purchase_options_remove_purchase_purchase_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Código de Prorrateo')),
                ('date', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Creación')),
                ('import_invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Factura de Importación')),
                ('import_invoice_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Factura')),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Póliza')),
                ('policy_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Póliza')),
                ('total_fob', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Total FOB')),
                ('freight', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Flete')),
                ('dai', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='DAI (Aranceles)')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Total Gastos al Costo')),
                ('total_prorated_cost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Costo Total Prorrateado')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.OneToOneField(blank=True, help_text='Seleccione la compra aprobada que desea prorratear.', null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchase', verbose_name='Compra a Prorratear')),
            ],
            options={
                'verbose_name': 'Prorrateo de Importación',
                'verbose_name_plural': 'Prorrateos de Importación',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProrationExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('FREIGHT', 'Flete'), ('DAI', 'DAI (Derechos Arancelarios)'), ('OTHER', 'Otro Gasto')], default='OTHER', max_length=10, verbose_name='Tipo de Gasto')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción del Gasto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('include_in_proration', models.BooleanField(default=True, help_text='Desmarque esta casilla si este gasto no debe afectar el costo del producto.', verbose_name='Incluir en Prorrateo')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='proration.proration')),
            ],
            options={
                'verbose_name': 'Gasto de Importación (Bitácora)',
                'verbose_name_plural': 'Gastos de Importación (Bitácora)',
            },
        ),
        migrations.CreateModel(
            name='ProrationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('fob_unit_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor FOB Unitario')),
                ('cost_percentage', models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8, verbose_name='% de Participación')),
                ('total_fob_value', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Valor FOB Total')),
                ('prorated_freight', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Flete Prorrateado')),
                ('prorated_dai', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='DAI Prorrateado')),
                ('prorated_other_expenses', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Otros Gastos Prorrateados')),
                ('prorated_unit_cost', models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=12, verbose_name='Costo Unitario Prorrateado')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Producto')),
                ('proration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proration.proration')),
            ],
            options={
                'verbose_name': 'Ítem de Prorrateo',
                'verbose_name_plural': 'Ítems de Prorrateo',
            },
        ),
    ]
