# Generated by Django 5.2 on 2025-10-12 06:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_product_subcategory'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Código de Retaceo')),
                ('date', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Creación')),
                ('origin_country', models.CharField(max_length=100, verbose_name='País de Origen')),
                ('import_invoice_number', models.CharField(max_length=100, verbose_name='Factura de Importación')),
                ('import_invoice_date', models.DateField(verbose_name='Fecha de Factura')),
                ('policy_number', models.CharField(max_length=100, verbose_name='Póliza')),
                ('policy_date', models.DateField(verbose_name='Fecha de Póliza')),
                ('total_fob', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Total FOB')),
                ('freight', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Flete')),
                ('dai', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='DAI (Aranceles)')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Total Gastos al Costo')),
                ('total_prorated_cost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Costo Total Retaceado')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Retaceo de Importación',
                'verbose_name_plural': 'Retaceos de Importación',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProrationExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('FREIGHT', 'Flete'), ('DAI', 'DAI (Derechos Arancelarios)'), ('OTHER', 'Otro Gasto')], default='OTHER', max_length=10, verbose_name='Tipo de Gasto')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción del Gasto')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('include_in_proration', models.BooleanField(default=True, help_text='Desmarque esta casilla si este gasto no debe afectar el costo del producto.', verbose_name='Incluir en Retaceo')),
                ('proration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='proration.proration')),
            ],
            options={
                'verbose_name': 'Gasto de Importación (Bitácora)',
                'verbose_name_plural': 'Gastos de Importación (Bitácora)',
            },
        ),
        migrations.CreateModel(
            name='ProrationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('fob_unit_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor FOB Unitario')),
                ('total_fob_value', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Valor FOB Total')),
                ('prorated_freight', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Flete Prorrateado')),
                ('prorated_dai', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='DAI Prorrateado')),
                ('prorated_other_expenses', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Otros Gastos Prorrateados')),
                ('prorated_unit_cost', models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=12, verbose_name='Costo Unitario Retaceado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Producto')),
                ('proration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proration.proration')),
            ],
            options={
                'verbose_name': 'Ítem de Retaceo',
                'verbose_name_plural': 'Ítems de Retaceo',
            },
        ),
    ]
