# Generated by Django 5.2 on 2025-10-12 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proration', '0001_initial'),
        ('purchase', '0004_alter_purchase_options_remove_purchase_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proration',
            options={'ordering': ['-date'], 'verbose_name': 'Prorrateo de Importación', 'verbose_name_plural': 'Prorrateos de Importación'},
        ),
        migrations.AlterModelOptions(
            name='prorationitem',
            options={'verbose_name': 'Ítem de Prorrateo', 'verbose_name_plural': 'Ítems de Prorrateo'},
        ),
        migrations.RemoveField(
            model_name='proration',
            name='origin_country',
        ),
        migrations.RemoveField(
            model_name='proration',
            name='provider',
        ),
        migrations.AddField(
            model_name='proration',
            name='purchase',
            field=models.OneToOneField(default=1, help_text='Seleccione la compra aprobada que desea prorratear.', on_delete=django.db.models.deletion.PROTECT, to='purchase.purchase', verbose_name='Compra a Prorratear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proration',
            name='code',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Código de Prorrateo'),
        ),
        migrations.AlterField(
            model_name='proration',
            name='total_prorated_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='Costo Total Prorrateado'),
        ),
        migrations.AlterField(
            model_name='prorationexpense',
            name='include_in_proration',
            field=models.BooleanField(default=True, help_text='Desmarque esta casilla si este gasto no debe afectar el costo del producto.', verbose_name='Incluir en Prorrateo'),
        ),
        migrations.AlterField(
            model_name='prorationitem',
            name='prorated_unit_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=12, verbose_name='Costo Unitario Prorrateado'),
        ),
    ]
