# Generated by Django 5.2 on 2025-10-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proration',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Marcar cuando el prorrateo esté finalizado y listo para el análisis de precios.', verbose_name='Prorrateo Aprobado'),
        ),
    ]
