# Generated by Django 5.2 on 2025-10-12 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proration', '0002_alter_proration_options_alter_prorationitem_options_and_more'),
        ('purchase', '0004_alter_purchase_options_remove_purchase_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prorationitem',
            name='cost_percentage',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=8, verbose_name='% de Participación'),
        ),
        migrations.AlterField(
            model_name='proration',
            name='purchase',
            field=models.OneToOneField(blank=True, help_text='Seleccione la compra aprobada que desea prorratear.', null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchase', verbose_name='Compra a Prorratear'),
        ),
    ]
