# Generated by Django 5.2 on 2025-10-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proration', '0003_prorationitem_cost_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proration',
            name='import_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Factura'),
        ),
        migrations.AlterField(
            model_name='proration',
            name='import_invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Factura de Importación'),
        ),
        migrations.AlterField(
            model_name='proration',
            name='policy_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Póliza'),
        ),
        migrations.AlterField(
            model_name='proration',
            name='policy_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Póliza'),
        ),
    ]
