# Generated by Django 5.2 on 2025-11-27 23:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellidos')),
                ('dui', models.CharField(help_text='Formato requerido: 00000000-0', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El DUI debe tener el formato correcto: 00000000-0', regex='^\\d{8}-\\d{1}$')], verbose_name='DUI')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone', models.CharField(help_text='Formato requerido: 0000-0000', max_length=9, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener el formato: 0000-0000', regex='^\\d{4}-\\d{4}$')], verbose_name='teléfono')),
                ('address', models.TextField(verbose_name='dirección completa')),
                ('department', models.CharField(choices=[('AH', 'Ahuachapán'), ('SA', 'Santa Ana'), ('SO', 'Sonsonate'), ('CH', 'Chalatenango'), ('LL', 'La Libertad'), ('SS', 'San Salvador'), ('CU', 'Cuscatlán'), ('LP', 'La Paz'), ('CA', 'Cabañas'), ('SV', 'San Vicente'), ('US', 'Usulután'), ('SM', 'San Miguel'), ('MO', 'Morazán'), ('LU', 'La Unión')], default='SS', max_length=2, verbose_name='departamento')),
                ('municipality', models.CharField(max_length=100, verbose_name='municipio')),
                ('is_tax_contributor', models.BooleanField(default=False, help_text='Marcar si el cliente requiere Comprobante de Crédito Fiscal (CCF).', verbose_name='es contribuyente (Crédito Fiscal)')),
                ('nrc', models.CharField(blank=True, help_text='Número de Registro de Contribuyente. Obligatorio si pide Crédito Fiscal.', max_length=50, null=True, verbose_name='NRC')),
                ('business_line', models.CharField(blank=True, help_text='Actividad económica. Obligatorio si pide Crédito Fiscal.', max_length=200, null=True, verbose_name='giro')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'client',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
