# Generated by Django 5.2 on 2025-11-27 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('product', '0003_alter_product_subcategory'),
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='código')),
                ('date', models.DateTimeField(verbose_name='fecha de traslado')),
                ('status', models.CharField(choices=[('picking', 'En Preparación (Picking)'), ('transit', 'En Tránsito'), ('received', 'Recibida Completa')], default='picking', max_length=20, verbose_name='estado')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('dest_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='branch.branch', verbose_name='destino')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to='branch.branch', verbose_name='origen')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'Transferencia',
                'verbose_name_plural': 'Transferencias',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransferDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.PositiveIntegerField(verbose_name='cantidad solicitada')),
                ('sent_quantity', models.PositiveIntegerField(default=0, verbose_name='cantidad enviada')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='cantidad recibida')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='comentario')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='producto')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transfers.transfer')),
            ],
        ),
    ]
