# Generated by Django 5.2 on 2025-11-25 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Ventas, Compras, Devolución, Avería.', max_length=100, unique=True, verbose_name='nombre del movimiento')),
                ('code', models.CharField(help_text='Código único para referencia (Ej: TRAS-ENT, VENT, COMP).', max_length=50, unique=True, verbose_name='código interno')),
                ('flow', models.CharField(choices=[('in', 'Entrada (+)'), ('out', 'Salida (-)')], help_text='Determina si este movimiento aumenta o disminuye el stock.', max_length=10, verbose_name='flujo de inventario')),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del motivo del movimiento.', null=True, verbose_name='descripción')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento',
                'verbose_name_plural': 'Tipos de Movimientos',
                'db_table': 'inventory_movement_type',
                'ordering': ['name'],
            },
        ),
    ]
