# Generated by Django 5.2 on 2025-11-27 00:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Ej: Toyota, Isuzu, Kia', max_length=50, verbose_name='marca')),
                ('model', models.CharField(help_text='Ej: Hilux, NPR, Forte', max_length=50, verbose_name='modelo')),
                ('year', models.PositiveIntegerField(help_text='Año de fabricación del vehículo.', validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2026)], verbose_name='año')),
                ('plate', models.CharField(help_text='Número de placa único (se guardará en mayúsculas).', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La placa debe contener solo letras mayúsculas, números y guiones (sin espacios). Ej: P-123-456, C123456', regex='^[A-Z0-9-]{3,10}$')], verbose_name='placa / matrícula')),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motocicleta'), ('sedan', 'Sedán / Pick-up'), ('panel', 'Panel de Carga'), ('light_truck', 'Camión Ligero (< 5 Ton)'), ('heavy_truck', 'Camión Pesado (> 5 Ton)')], default='sedan', max_length=20, verbose_name='tipo de vehículo')),
                ('max_capacity_kg', models.DecimalField(decimal_places=2, default=0, help_text='Peso máximo que soporta el vehículo.', max_digits=10, verbose_name='capacidad máx. (Kg)')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre del conductor asignado')),
                ('description', models.TextField(blank=True, help_text='Detalles adicionales, estado mecánico, etc.', null=True, verbose_name='observaciones')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehicle',
                'ordering': ['plate'],
            },
        ),
    ]
