# Generated by Django 5.2 on 2025-11-27 23:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
        ('client', '0001_initial'),
        ('product', '0003_alter_product_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='código')),
                ('sale_type', models.CharField(choices=[('FCF', 'Factura Consumidor Final'), ('CCF', 'Comprobante de Crédito Fiscal')], default='FCF', max_length=3, verbose_name='tipo de documento')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('status', models.CharField(choices=[('draft', 'Borrador (Cotizando)'), ('completed', 'Finalizada (Facturada)')], default='draft', max_length=20, verbose_name='estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='IVA (13%)')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12, verbose_name='total a pagar')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='branch.branch', verbose_name='sucursal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='client.client', verbose_name='cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'sale',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='descuento ($)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sale.sale')),
            ],
        ),
    ]
