# Generated by Django 5.2 on 2025-11-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_saledetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='precio unitario'),
        ),
    ]
