# Generated by Django 5.2 on 2025-11-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_saledetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='descuento (%)'),
        ),
    ]
