# Generated by Django 5.2 on 2025-10-12 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proration', '0004_alter_proration_import_invoice_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Código de Análisis')),
                ('invoice_number', models.CharField(editable=False, max_length=100, verbose_name='Factura de Compra')),
                ('is_approved', models.BooleanField(default=False, help_text='Marcar para generar y activar los nuevos precios en el historial.', verbose_name='Análisis Aprobado')),
                ('date', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Análisis')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='proration.proration', verbose_name='Prorrateo de Origen')),
            ],
            options={
                'verbose_name': 'Análisis de Precio',
                'verbose_name_plural': 'Análisis de Precios',
                'ordering': ['-date'],
            },
        ),
    ]
