# Generated by Django 5.2 on 2025-10-13 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price_analysis', '0001_initial'),
        ('proration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceanalysis',
            name='proration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='proration.proration', verbose_name='Prorrateo de Origen'),
        ),
    ]
