# Generated by Django 5.2 on 2025-08-10 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
        ('quotation', '0002_alter_quotation_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='provider.provider', verbose_name='proveedor'),
        ),
    ]
