# Generated by Django 5.2 on 2025-10-12 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buy_order', '0004_alter_buyorder_quotation'),
        ('provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Número de factura o comprobante de crédito fiscal.', max_length=100, unique=True, verbose_name='número de factura')),
                ('purchase_date', models.DateField(editable=False, verbose_name='fecha de compra')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('buy_order', models.ForeignKey(help_text='Orden de compra a partir de la cual se genera esta compra.', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='buy_order.buyorder', unique=True, verbose_name='orden de compra')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('provider', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='provider.provider', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'purchase',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
