# Generated by Django 5.2 on 2025-10-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchase_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Marcar si la compra ha sido aprobada.', verbose_name='aprobada'),
        ),
    ]
