# Generated by Django 5.2 on 2025-10-12 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='purchase',
            name='code',
            field=models.CharField(blank=True, editable=False, help_text='Código único generado automáticamente para la compra.', max_length=100, unique=True, verbose_name='código de compra'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=datetime.date(2025, 10, 11), verbose_name='fecha de compra'),
            preserve_default=False,
        ),
    ]
