# Generated by Django 5.2 on 2025-11-25 01:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchase_options_remove_purchase_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='batch',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Código de lote único generado automáticamente.', unique=True, verbose_name='lote (batch)'),
        ),
    ]
