# Generated by Django 5.2 on 2025-11-26 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_order', '0006_alter_buyorder_is_approved'),
        ('purchase', '0005_purchase_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='buy_order',
            field=models.ForeignKey(help_text='Orden de compra a partir de la cual se genera esta compra.', on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='buy_order.buyorder', unique=True, verbose_name='orden de compra'),
        ),
    ]
