# Generated by Django 5.2 on 2025-08-07 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('subcategory', '0001_initial'),
        ('unit_of_measure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('code', models.CharField(blank=True, editable=False, help_text='Código único generado automáticamente para el producto.', max_length=100, unique=True, verbose_name='código de producto')),
                ('sku', models.CharField(help_text='Código único de referencia para el inventario, usualmente del proveedor.', max_length=100, unique=True, verbose_name='SKU (Stock Keeping Unit)')),
                ('name', models.CharField(max_length=100, verbose_name='nombre del producto')),
                ('size', models.CharField(max_length=100, verbose_name='talla o dimensión')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('presentation', models.CharField(max_length=100, verbose_name='presentación')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='category.category', verbose_name='categoría')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('purchase_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='unit_of_measure.unitofmeasure', verbose_name='unidad de compra')),
                ('sale_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='unit_of_measure.unitofmeasure', verbose_name='unidad de venta')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='subcategory.subcategory', verbose_name='subcategoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
    ]
