# Generated by Django 5.2 on 2025-10-12 04:55

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_created_by_alter_product_modified_by_and_more'),
        ('subcategory', '0002_alter_subcategory_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.PROTECT, to='subcategory.subcategory', verbose_name='subcategoría'),
        ),
    ]
