# Generated by Django 5.2 on 2025-11-25 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nombre de sucursal')),
                ('branch_type', models.CharField(choices=[('storage', 'Bodega'), ('branch', 'Sucursal')], default='branch', max_length=20, verbose_name='tipo')),
                ('address', models.TextField(help_text='Dirección física detallada.', verbose_name='dirección completa')),
                ('department', models.CharField(choices=[('AH', 'Ahuachapán'), ('CB', 'Cabañas'), ('CH', 'Chalatenango'), ('CU', 'Cuscatlán'), ('LL', 'La Libertad'), ('LP', 'La Paz'), ('LU', 'La Unión'), ('MO', 'Morazán'), ('SM', 'San Miguel'), ('SS', 'San Salvador'), ('SV', 'San Vicente'), ('SA', 'Santa Ana'), ('SO', 'Sonsonate'), ('US', 'Usulután')], default='SS', max_length=2, verbose_name='departamento')),
                ('municipality', models.CharField(help_text='Ej: Santa Tecla, Antiguo Cuscatlán, etc.', max_length=100, verbose_name='municipio')),
                ('phone', models.CharField(blank=True, help_text='Teléfono de contacto de la sucursal.', max_length=20, null=True, verbose_name='teléfono')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'branch',
                'ordering': ['name'],
            },
        ),
    ]
