# Generated by Django 5.2 on 2025-10-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='is_received',
            field=models.BooleanField(default=False, help_text='Marcar si este ítem específico ha sido recibido.', verbose_name='recibido'),
        ),
    ]
