# Generated by Django 5.2 on 2025-11-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_detail', '0002_purchasedetail_is_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedetail',
            name='verified_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad real contada físicamente en bodega.', verbose_name='cantidad verificada'),
        ),
    ]
